name: wallpaper_app
description: Ultra-modern Pinterest-style wallpaper app using Pexels API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.6
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  share_plus: ^7.2.1
  permission_handler: ^11.0.1

  dio: ^5.4.0
  path_provider: ^2.1.3
  gal: ^2.3.2   # â­ New working gallery saver plugin

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
